spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show_sql: false
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings.trace: false
      settings.web-allow-others: true
  sql:
    init:
      mode: always
app:
  token:
    secret: my-secret-key
    expirationMs: 86400000