spring:
  datasource:
    url: jdbc:mysql://mysql-docker-container:3306/test_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: mysql
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show_sql: false
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
app:
  token:
    secret: my-secret-key
    expirationMs: 86400000